export enum ErrorCodes {
  // Ticket errors
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  NO_TICKETS_AVAILABLE = 'NO_TICKETS_AVAILABLE',
  INVALID_TICKET_STATUS = 'INVALID_TICKET_STATUS',
  
  // Passenger errors
  INVALID_PASSENGER_DATA = 'INVALID_PASSENGER_DATA',
  TOO_MANY_CHILDREN = 'TOO_MANY_CHILDREN',
  
  // System errors
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}